rm(list = ls()) # Clear the environment's variables

RequirePackages <- function(packages) { # if package is installed import it else install it and import it
  lapply(packages, function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)
    }
  })
}

map <- list(
  A = "l'age",
  B = "le sexe",
  C = "le niveau d'etude",
  D = "l'ecole/La faculte",
  F1 = "l'utilisation de Google Classroom",
  F2 = "l'utilisation de Moodle",
  F3 = "l'utilisation de Google Meet",
  F4 = "l'utilisation de Zoom",
  F5 = "l'utilisation de Microsoft Team",
  H1 = "la preference de Google Classroom",
  H2 = "la preference de Moodle",
  H3 = "la preference de Google Meet",
  H4 = "la preference de Zoom",
  H5 = "la preference de Microsoft Team",
  G1 = "l'utilisation d'un ordinateur bureau",
  G2 = "l'utilisation d'un ordinateur portable",
  G3 = "l'utilisation d'un telephone portable",
  G4 = "l'utilisation d'une tablette",
  I1 = "les problemes lies a la perte de connexion ou debit faible",
  I2 = "les problemes lies a la manipulation des plateformes",
  I3 = "les problemes lies a la coupure d'electricite",
  I4 = "les problemes lies au blocage de l'ordinateur",
  I5 = "les problemes lies a l'indisponibilite des appareils",
  J = "le nombre de seance etudiees par semaine",
  K1 = "le fait que durant l'enseignement a distance les devoirs sont devenus nombreux",
  k2 = "le fait que durant l'enseignement a distance les cours sont plus difficile a suvire",
  k3 = "le fait que durant l'enseignement a distance les cours posent les etudiants sur la bonne voie pour s'approfondir",
  k4 = "le fait que durant l'enseignement a distance les etudiants assimilent les cours",
  M1 = "le fait que les cours sont plus sous forme de cours interactives",
  M2 = "le fait que les cours sont plus sous forme de visioconferences",
  M3 = "le fait que les cours sont plus sous forme de cours PDF/PPT telechargeables",
  M4 = "le fait que les cours sont plus sous forme de videos telechargeables",
  O1 = "la preference des cours interactives",
  O2 = "la preference des visioconferences",
  O3 = "la preference des cours PDF/PPT telechargeables",
  O4 = "la preference des videos telechargeables",
  P1 = "le fait que les enseignants sont bien formes pour assurer des cours a distance",
  P2 = "le fait que les enseignants respectent les horaires",
  P3 = "le fait que les eleves respectent les horaires",
  P4 = "le fait que les enseignants s'assurent de l'assiduite des eleves",
  P5 = "le fait d'avoir une excellente assiduite durant les cours à distance",
  P6 = "le fait de gerer bien le temps",
  P7 = "le fait de dormir plus",
  Q1 = "le fait que les enseignants s'assurent de l'assiduite des eleves a l'aide des quiz",
  Q2 = "le fait que les enseignants s'assurent de l'assiduite des eleves a l'aide de l'appel",
  Q3 = "le fait que les enseignants s'assurent de l'assiduite des eleves a l'aide des questions durant le cours",
  R1 = "l'impact de l'enseignement a distance durant le confinement sur la productivite",
  R2 = "l'impact de l'enseignement a distance durant le confinement sur l'innovation",
  R3 = "l'impact de l'enseignement a distance durant le confinement sur la creativite",
  R4 = "l'impact de l'enseignement a distance durant le confinement sur le stress",
  R5 = "l'impact de l'enseignement a distance durant le confinement sur l'anxiete",
  R6 = "l'impact de l'enseignement a distance durant le confinement sur l'ennui",
  R7 = "l'impact de l'enseignement a distance durant le confinement sur la depression",
  R8 = "l'impact de l'enseignement a distance durant le confinement sur la concentration",
  S1 = "la preference des examens a distance",
  S2 = "la preference des examens en presentiel",
  S3 = "la preference des examens sous forme de questions ouvertes",
  S4 = "la preference des examens sous forme de questions a choix multiples",
  S5 = "la preference des examens sous forme de projet",
  S6 = "la preference des examens sous forme d'exercices",
  S7 = "la preference des examens sous forme d'evaluation orale",
  N = "L'impacte de l'enseignement a distance durant le confinement sur le classement/mobilite/double diplomation",
  L1 = "la preference des cours en presentiel/distance sous les conditions actuelles",
  L2 = "la preference des cours en presentiel/distance apres amelioration des conditions"
)
